// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0euCkJepKNW4aqpY1mKqJhbNf4DYOCwI',
    appId: '1:590694135686:web:50ac1d1557d60b10189e07',
    messagingSenderId: '590694135686',
    projectId: 'harvesthub-mobile-app',
    authDomain: 'harvesthub-mobile-app.firebaseapp.com',
    storageBucket: 'harvesthub-mobile-app.firebasestorage.app',
    measurementId: 'G-MM932PHDNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhqAdVVZTvV0PxY9PHeGIMAxlXqWvuESM',
    appId: '1:590694135686:android:ea90215d908d1978189e07',
    messagingSenderId: '590694135686',
    projectId: 'harvesthub-mobile-app',
    storageBucket: 'harvesthub-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfarODXi3pvqLq0EYR9T4P_QD4L7K6Eck',
    appId: '1:590694135686:ios:352575e7a11569be189e07',
    messagingSenderId: '590694135686',
    projectId: 'harvesthub-mobile-app',
    storageBucket: 'harvesthub-mobile-app.firebasestorage.app',
    iosBundleId: 'com.theharvesthub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfarODXi3pvqLq0EYR9T4P_QD4L7K6Eck',
    appId: '1:590694135686:ios:352575e7a11569be189e07',
    messagingSenderId: '590694135686',
    projectId: 'harvesthub-mobile-app',
    storageBucket: 'harvesthub-mobile-app.firebasestorage.app',
    iosBundleId: 'com.theharvesthub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0euCkJepKNW4aqpY1mKqJhbNf4DYOCwI',
    appId: '1:590694135686:web:b96184d159703edc189e07',
    messagingSenderId: '590694135686',
    projectId: 'harvesthub-mobile-app',
    authDomain: 'harvesthub-mobile-app.firebaseapp.com',
    storageBucket: 'harvesthub-mobile-app.firebasestorage.app',
    measurementId: 'G-7W0W5ZZDW7',
  );
}
